"""model notes_id should be unique

Revision ID: 622487b3eedb
Revises: d5e1d4351689
Create Date: 2026-10-07 21:27:38.123897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '622487b3eedb'
down_revision: Union[str, Sequence[str], None] = 'd5e1d4351689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'notes', ['user_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='unique')
    # ### end Alembic commands ###
