"""add new_column to notes

Revision ID: d5e1d4351689
Revises: 001_rename_notes_id
Create Date: 2026-09-29 21:18:52.641690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5e1d4351689'
down_revision: Union[str, Sequence[str], None] = '001_rename_notes_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('quiz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'quiz')
    # ### end Alembic commands ###
